name: Integration Tests

on: push

jobs:
  #build:
  #  name: Compile Firmware
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/cache@v4
  #      with:
  #        path: |
  #          ~/.cache/pip
  #          ~/.platformio/.cache
  #        key: compile-cache
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version: '3.10'
  #    - name: Install PlatformIO
  #      shell: bash
  #      run: |
  #        python -m pip install --upgrade pip
  #        pip install --upgrade platformio
#
  #    - name: Checkout code
  #      uses: actions/checkout@v4
  #    - name: Build PlatformIO Project
  #      run: pio run
  #    - name: Upload artifacts
  #      uses: actions/upload-artifact@v3
  #      with:
  #        name: firmware
  #        path: .pio/build/lora_board/firmware.bin

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.10.2
        with:
          clang-format-version: '14'
          check-path: src

  cppcheck:
    name: Run cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: check-cache
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install PlatformIO
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run PlatformIO Check
        run: pio check --fail-on-defect high --fail-on-defect medium --fail-on-defect low -e ttgo-lora32

  hw_testing:
    name: Hardware Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: check-cache
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install PlatformIO
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run PlatformIO Check
        run: pio remote test --environment ttgo-lora32
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}

    
